### PR TITLE
Version 2 fixes

### PR DESCRIPTION
**Pull request by mheffner**
Misc fixes required to get a minimal 0.7.4 Cassandra cluster bootstrapped.

### CODE REVIEW

**Comment by mrflip** [comment]
Sigh, let these drift too far.
I went through and cherry-picked out what seemed to be the fixes, leaving two behind:
- NTP, because there was an inconsistency,
- Cluster facet indexes, because it changed the semantics 
  I've filed bugs for each of them.

**Comment by mheffner** [comment]
Yeah, we've been fairly driven towards getting our cassandra cluster up. I've been meaning to extract our changesets into logical chunks and send pull requests.

BTW, given master is marked deprecated, are you planning to merge version2 in?

**Comment by mrflip** [comment]
If version_2_fixes is your production branch I only see two small diffs to it from our version_2, so you should be clean to pull from it. In infochimps/cluster_chef#16 I summarized the flurry of git merges I made today. 

We are indeed going to move to version_2 being the official branch - but it has to happen while keeping our production servers stable.  We'll be tracking the planning and evolution of the changes using the github issues so that you can stay abreast of what changes, and we'll try to flag anything that could be breaking.

In infochimps/cluster_chef#10 and infochimps/cluster_chef#14 is a summary of the high-level changes we plan.

**Comment by mheffner** [comment]
I'd recommend pulling the following (just pushed) revert. It was 
something we were using while tracking down an issue but is not 
generally applicable.

commit 8def3eefd9cb502441007e1371191f2561fdadeb
Author: Mike Heffner mikeh@fesnel.com
Date:   Sun May 15 17:16:44 2011 -0400

```
 This doesn't belong here, recommendation is to not use Ubuntu 10.04.

 Revert "XXX: Add hack to abort bootstrapping on nodes with the 5507 
```

chip. See:"

```
 This reverts commit 9aa6ffd9d6a9b6ccf336e4296379f341c12345cf.
```

On 05/14/2011 11:25 PM, mrflip wrote:

> If version_2_fixes is your production branch I only see two small diffs to it from our version_2, so you should be clean to pull from it. In infochimps/cluster_chef#16 I summarized the flurry of git merges I made today.
> 
> We are indeed going to move to version_2 being the official branch - but it has to happen while keeping our production servers stable.  We'll be tracking the planning and evolution of the changes using the github issues so that you can stay abreast of what changes, and we'll try to flag anything that could be breaking.
> 
> In infochimps/cluster_chef#10 and infochimps/cluster_chef#14 is a summary of the high-level changes we plan.

Mike

## 

   Mike Heffner   mikeh@fesnel.com

**Pull request closed without merging**
