### PR TITLE
Allow per-ephemeral-disk options using :disks attribute

### PR DESCRIPTION
**Pull request by nickmarden**
This is the (simple) concrete version of what I mentioned on the ironfan-users mailing list.

In effect, this allows you to provide volume attributes, on a per-ephemeral-disk basis. My own motivation was to be able to override the :mount_point attribute.

### CODE REVIEW

**Comment by mrflip** [comment]
mount_ephemerals is just a wrapper around a set of calls to `volume`, same as other calls to `volume`.

You should be able to say `volumes(:ephemeral0).mount_point '/foo/bar'` (not tested, please pardon typos). Can you find out if this works?

A hash here seems like sugar on sugar. I think we're better off getting at the volumes directly, but that's not a passionate opinion.

**Comment by temujin9** [comment]
:+1: for using existing semantics, if possible. I think it should work.

**Comment by nickmarden** [comment]
It _does_ work, but it's very un-DRY. Why? Because I can't (or at least I believe I can't) specify #volume calls at the cluster level. 

To put numbers on the size of this problem: my cluster has 18 clusters, 16 of which I would like to have mount two of their ephemeral disks in specific locations. To achieve this with #volume calls in the different facets would be 2_12_16= 384 lines of cluster file cut-and-pasta.

In contrast, doing it with my proposed syntactic sugar would be +5 lines in the cluster cloud(:ec2) section and +6 lines in the two facets that want different behavior.

**Comment by nickmarden** [comment]
Oh - and one other thing I forgot to mention. Mounting a single ephemeral volume manually with a #volume call disallows the possibility of a cluster- or facet-level #mount_ephemerals call, or at least makes its behaviors unpredictable. So, if you want to do something like set some global ephemerals :tags with a cluster-level mount_ephemerals call, it will actually stomp on the volume('ephemeral0') call inside a specific facet.

This syntactic sugar also happens to resolve that stomping ambiguity.

**Comment by temujin9** [comment]
@nickmarden - thanks for explaining further.

@mrflip - the underlying problems he's got with ephemerals sounds very much like a complicated interaction between the resolve code and the way `mount_ephemerals` works. We definitely need fixing the resolve code to be a priority Real Soon Now: the vSphere provider approacheth, and its also causing many other issues (like this).

**Comment by nickmarden** [comment]
So...I have a project under way right now to handle this not-relocatable-software problem for our production cluster, and I'm hoping to get some guidance about which way you guys think this pull request will go.

There would and should be some push-back here at Get Satisfaction if I propose the +384 line approach described above. Since I _really really_ strongly prefer not to run a non-mainstream version of ironfan core in Get Satisfaction's ironfan-homebase, please allow me to rephrase my pull request rationale in the hopes of swaying you:

"Since #mount_ephemerals is a syntactic sugar replacement for multiple calls to #volume, it should either support the full set of configuration parameters for each individual volume (this pull request), or it should be possible to declare volume behaviors at a cluster level in order to keep cluster definitions dry. The former is simple, whereas the latter would probably have far-reaching DSL implications."

Also, please note that I batted my eyelashes while saying that. And that I'm cute.

**Comment by mrflip** [comment]
Gotcha. Framing what you're doing here as passing options down through the
sugar shows it as a perfectly sane way to do this.  And even if it wasn't,
avoiding the N^2 ball of overrides you described says "apologize to the
dentist later, add the sugar".

Objections removed.

flip

**Comment by temujin9** [comment]
Sold. It'll be in the next gem I cut.

**Comment by temujin9** [comment]
(Which might be a little while . . . http://tinyurl.com/anqa5s5 )

**Comment by temujin9** [comment]
Okay, gem cut and pushed, finally. Thanks again.

**Pull request merged**
