### PR TITLE
Re-enables integration specs, explicitly excluding them from "rake spec"

### PR DESCRIPTION
**Pull request by nickmarden**

### CODE REVIEW

**Comment by temujin9** [comment]
Problem with the missing-file issue is that gemspec complains when trying to cut a new gem. We need a different mechanism to reference the "might be missing" file.

**Comment by nickmarden** [comment]
I'm not sure what you mean. The missing file (knife-user-ironfantester.rb) isn't referenced as a "require" statement anywhere. Its existence is a bit of a state secret that gemspec couldn't possibly know about.

Can you tell me how to reproduce the issue you're seeing?

**Comment by temujin9** [comment]
I think the .pem files were dangling symlinks the first time. They work fine now (from a gem-cutting perspective), but they are also full of actual credentials . . . are you sure you want to publish those?

**Comment by temujin9** [comment]
(If they're the credentials you use for the VCR, and you turn them off on IAM on your end, it should be okay: I just want to be certain before I cut the gem.)

**Comment by nickmarden** [comment]
The pem files in question - ironfantest-validator.pem and ironfantester.pem - are credentials for a free OpsCode Hosted Chef account. They are intended to be shared between people who want to run the integration test.

What _shouldn't_ be present in the commit is the file knife-user-ironfantester.rb. It contains the sensitive AWS credentials that could be abused if published on the Interwebs.

**Comment by temujin9** [comment]
Ah, yes, you're right: those are Opscode, not AWS. Cutting the gem now.

**Pull request merged**
