### PR TITLE
Make vagrant ip settings work from knife-org.rb

### PR DESCRIPTION
**Pull request by jasherai**
Still very new to ironfan, so please let me know if this needs adjusting!

---

use host_network_base in cluster_vagrant.rb to use the definable value
in knife.org

fixup ip_for method to look up the correct ip mapping for the facet
being launched.

### CODE REVIEW

**Comment by mrflip** [comment]
Looks good. This issue of "facets need a magic disambiguating number" crops up in Zookeeper too. Passing around a magic config variable is unbeautiful, but works.

+1

**Comment by mrflip** [comment]
To be clear: your patch is fine; the 'unbeautiful' part is that Ironfan doesn't define a graceful way to get that number. :)

The next time we see this use case crop will make three, which will mean it's time to put a clean abstraction into ironfan.

**Comment by temujin9** [comment]
Merged, with the caveat that the ugliness should be expected to change, in possibly breaking ways, once we find a nicer way to handle that.

**Comment by jasherai** [comment]
Awesome! Hoping you have ideas for cleaning up the ugliness!

**Pull request merged**
