### PR TITLE
Use public ip and hostname for host lookup. Fixes infochimps-labs/ironfan#328

### PR DESCRIPTION
**Pull request by kornypoet**
To the maintainer: please review this commit, but delay pulling in until _after_ January 1st, 2014 due to release schedules.

### CODE REVIEW

**Comment by lindseybaron** [comment]
Can this be un-delayed now?

**Comment by kornypoet** [comment]
Absolutely. Whoever is in charge is welcome to pull it in.

**Comment by joshbronson** [comment]
I will take a test this out after I'm done putting out fires, but I don't have a test environment set up right this moment. If someone would like to test this more quickly, here are the instructions for testing this change:
1. Change the line <code>gem 'ironfan',         "~> 5.0.0"</code> in your homebase to <code>gem 'ironfan', path: '../ironfan'</code>
2. Clone travis' change there:
   1. <code>$ cd ..</code>
   2. <code>$ git clone -b cluster_kick git@github.com:korneypoet/ironfan.git ironfan</code>
3. Use <code>bundle exec</code> to execute commands as before. Make sure <code>cluster_ssh</code> works as expected.

If it works for one other person, I'll take a quick look at the code, merge it in, and cut a gem. Anyone else with the ability to cut an Ironfan gem is welcome to do so before me.

**Comment by lindseybaron** [comment]
Kick seems to work for me, either with -x and -i, or as myself, then enter password at prompt.

Haven't tried ssh yet, though.

**Pull request merged**
