### PR TITLE
Use the Ironfan hostname for cluster_ssh

### PR DESCRIPTION
**Pull request by meekmichael**
Replaces the native hostname of the underlying cloud provider
with the Ironfan hostname when running ssh or kick commands.

### CODE REVIEW

**Comment by nickmarden** [comment]
+1!

**Comment by temujin9** [comment]
This will need to be feature-flagged, and off by default: it's a change in behavior, which depends on DNS resolution (only ensured, currently, in AWS with Route53) to work. Otherwise, +1, will merge as soon as it's safe to.

**Comment by nickmarden** [comment]
How does it depend on DNS resolution? It perhaps depends on the machine having a public_hostname, but I don't see where it resolves that hostname.

**Comment by temujin9** [comment]
You're right, it doesn't rely on Route53; I read through too quickly. However, attempts to ssh via a public hostname rely on DNS being propagated. This is available by default on AWS, but not necessarily elsewhere (e.g - vSphere).

**Comment by temujin9** [comment]
Oh, bugger, now I see what you're saying. This is just a display hack, not to do with the actual SSH. Lemme test it, and then I'll probably merge. Sorry; was relying too much on the description, not enough on the code.

**Pull request merged**
