### PR TITLE
Correct merging of cluster and facet objects, with specs (fixes #158)

### LINKED ISSUE #158: Security groups in facet misbehaving
The following definition results in an instance with the `sparky` and `sparky-web` security groups, but no `ssh` security group.

``` ruby
Ironfan.cluster "sparky" do
    cloud(:ec2).security_group(:ssh).authorize_port_range 22..22
    facet :web do
        cloud(:ec2).security_group("sparky-web").authorize_port_range(80)
    end
end
```

However, removing the security group definition from the web facet, creates an instance with the `ssh` group as well as the `sparky` and `sparky-web` groups. Facet security group definitions seem to be clobbering those defined in the cluster?

### PR DESCRIPTION
**Pull request by nickmarden**
This patch fixes the incorrect merging of the clouds collection, which was at the root of #158.

The basic idea is that, Gorillib::Resolution extensions to allow for deep merging didn't actually dig far enough into the Gorillib internals to ensure that cluster.clouds and facet.clouds would merge correctly. Furthermore,  a failure to deep_copy the underlay attributes at resolve-time was causing a corruption in the underlay (read: cluster) security group definitions which would, under certain circumstances, result in "correct behavior" insofar as the merge algorithm expectations were concerned.

This patch also moves much of the resolution and expansion of server information into the Ironfan.cluster call itself, to ensure that no downstream callers are responsible for calling things like cluster.resolve or cluster.expand_servers! in order to get a consistent view of a cluster.

Lastly, specs are added which assert some sane things about how multi-facet clusters should work, and proving that they now do.

### CODE REVIEW

**Comment by mrflip** [comment]
HOORAY SPECS. I'll do my best to get on that train.

I merged this branch with the other PRs I put in -- see https://github.com/infochimps-labs/ironfan/tree/cloud_merge_borkage

I expect @temujin9 will have to pore over this but I'll try to keep my next patches clean against infochimps-labs/cloud_merge_borkage and infochimps-labs/keypair_not_key_pair

PS In this case, with the gemspec / rakefile / etc changes it was probably appropriate, but I usually see open-source projects recommend against committing version bumps, as it can cause merge conflicts. I haven't been updating the changelog; instead I try to form changelog-ready commit titles and leave it to the maintainer to manage. Anyway if you'll forgive the digression -- @temujin9 what policy would you like us to follow wrt updating the changelog / gem version / gemspec on commits?

**Comment by mrflip** [comment]
I'm having a weird way-out-of-scale memory consumption thing happening; I don't know if it's in this code or the changes I made to collection types. I may not be able to take a hard look until Tuesday, but let me know if you notice this too.

**Comment by nickmarden** [comment]
Thanks for catching that @mrflip. The memory footprint issue that you're referring to is definitely real. Some poking around shows that it's caused by

https://github.com/nickmarden/ironfan/commit/63af0871fea3e7ec67318b9ba59c3390483fde3d#L0R139

which is - at present - a required line because it prevents corruption of copied underlay attributes. (Simply revert that single line and you'll see that the security group specs fail.)

I patched the code this way because of the following discovery: when cluster.clouds gets merged into facet.clouds, and then the facet.cloud(:ec2).security_groups are resolved, using a non-deep copy means that one particular facet's security_groups get overwritten onto the entire cloud's security groups. This is the root cause of #158.

I'm going to continue to look into to it to see if there is a simplifying assumption that can be introduced to achieve clean attributes while reducing memory bloat. In the meantime, I think that the code in my patch is more correct that the original code, albeit at the cost of a goofy memory footprint.

**Comment by nickmarden** [comment]
b01fc4c6 seems to reduce the memory footprint back to what it once was, by simply removing a whole bunch of unnecessary #resolve calls in favor of a single top-down cluster.resolve call at the end of the cluster loading process.

**Comment by temujin9** [comment]
Rock. On. 

Merged with extreme prejudice.

**Pull request merged**
