### PR TITLE
Ubuntu 12.04 bootstrap support (fixes #135)

### LINKED ISSUE #135: Support Ubuntu 12.04
I'm guessing this is already on the roadmap.  Is there a timeframe?  Is using the 11.10 bootstrap files likely to work in the meantime?

### PR DESCRIPTION
**Pull request by nickmarden**
This bootstrap template uses the Opscode-provided Chef installer in /opt/chef including a self-contained Ruby installation. This is done to work around the fact that the Chef client that ships with Ubuntu 12.04 has dependencies on the Ubuntu-provided Ruby 1.8.7 packages.

### CODE REVIEW

**Comment by temujin9** [comment]
Damn. I hate to say it, but I'm going to have to kick this one back.

That's a pretty big change for us: building Ruby 1.9.2-p290 from source (and installing chef via RubyGems) gives us a stable, uniform Ruby environment for later cookbooks. I know we went through hell with various different sources of ruby 1.8 before we standardized, which makes me loathe to experiment further. Sorry for not making those requirements explicit earlier; they'd faded into background assumptions, since we touch bootstrap so rarely. 

This does help illustrate the need for community repositories. This is good code, and will probably work fine for someone, but it isn't something I'd feel very comfortable supporting: we'd never use it internally, and it changes too many underlying assumptions to be predictable.

**Comment by nickmarden** [comment]
I'm fine with the rejection (I learned _something_ in high school I suppose)....BUT the existing ubuntu11.10 bootstrap doesn't install Ruby 1.9.2-p290 from source; it just installs whichever Ruby 1.9.1-ABI-compat is shipping with Ubuntu at that time.

It is true as you say that chef is then installed via RubyGems, and I'm fine with that requirement.

So we have three approaches:
1. Whatever you just alluded to, which I think is the ubuntu10.04 approach
2. The approach used in the ironfan repo's Ubuntu11.10 bootstrap script: use the Ubuntu-provided Ruby and then go to town using rubygems to install chef
3. The approach I suggested in this pull request

Since (3) isn't acceptable, would you prefer a convergence in the ironfan repo on (1) or (2)?

Also, as a total aside: would you consider it acceptable to make the activation "service chef-client start" an optional behavior? Many companies, including Get Satisfaction, have some computers on which automatic convergence isn't desirable because of the need to coordinate releases across multiple machines (e.g. web app updates). If so, my pull request could include support for that in Ubuntu 10.04, 11.10, and 12.04.

(Note: sorry for the edits; I realized after the fact that I had edited my comments poorly once I realized that the ubuntu10.04 bootstrap script was what you were referring to.)

**Comment by temujin9** [comment]
Well, there's egg on my face. Turns out we're using the 10.04 approach even on newer machines. That's the correct one, and I'm a bit irritated at the questionably compatible 11.10 script, now that I see its differences. Since its been in a while, I'm not going to rip it back out, but I'm probably going to be marking it all sorts of deprecated soon.

And if you shut off (or make configurable) the auto-start of chef-client in favor of something that runs it once at boot (so that the node gets repopulated correctly, and things like NFS mounts happen), I'd probably have to restrain myself from kissing you. That's a long-standing low level irritant internally, too.

**Comment by nickmarden** [comment]
Challenge considered.

**Pull request closed without merging**
