### PR TITLE
Tiny patch to update us-west-2 oneiric images to latest versions from Ubuntu (via alestic)

### PR DESCRIPTION
**Pull request by redbeard**

### CODE REVIEW

**Comment by mrflip** [comment]
@gchpaco can you +1 that this bump won't screw you up?

Traditionally I would just yank this in, the change would take effect at next bump of the gem (i.e. the image_name=image_id pairing might change from 3.0.9 to 3.0.10, but only because canonical changed its recommendation).

But since cluster chef is moving to have a more "ops-guy risk profile" release cycle, how should changes to this table be handled going forward? pro=yank it on in:
- con: it's a really easy thing to slip past someone -- "gee, I upgraded cluster chef gems and now different AMIs launch WTF".
- pro: AMI updates are very rare
- pro: if canonical thinks a new AMI version is the right one, so should we
- pro: the change in this case is to oneiric i.e. near-bleeding-edge. The risk profile and necessity of the patch are both likely high; if it were an update to lucid I'd wait til a point release
- pro: the conservative sysadmin is welcome to duplicate a line with a name that pins it down. I _don't_ want to decorate the names  - using the name means 'give me an oneiric system, you figure out the details'

so I say "keep the table current; updates happen at next release and don't require a bump in point version" -- but I want the sysadmins' unanimous vote not mine.

**Comment by gchpaco** [comment]
+1 to the idea, but that particular patch is incomplete, missing as it does all the other updated ones from Alestic (it's a pain, I know, but you can get them all in one place at http://cloud-images.ubuntu.com/releases/oneiric/release-20111205/).  The changes are, i believe, listed at http://groups.google.com/group/ec2ubuntu/browse_thread/thread/f0d77fa050378746# and largely look like security patches, so it is probably worthwhile upgrading.

**Comment by redbeard** [comment]
Fair enough-

I'll update the rest and send the pull request later as its
approaching midnight here.

Cheers,
Tal

On 23/12/2011, at 19:44, Graham Hughes
reply@reply.github.com
wrote:

**Comment by redbeard** [comment]
As per comment, updated the rest of the Oneiric image ids.

**Comment by redbeard** [comment]
Happy NY :)

**Pull request merged**
