### PR TITLE
Workaround for bundler swallowing the '--verbose' flag

### PR DESCRIPTION
**Pull request by mrflip**
Recent bundlers swallow the --verbose flag (bundler/issues#2102): 'bundle exec knife ... -VV'  never does get the verbositoseness all the way to knife.

I'm preparing a patch for bundler, but being blind to backtraces is horrible enough to justify a workaround:

If you specify '-Z' or '-ZZ' alone as an arg, it will be turned into '-V' or '-VV', resp. Arguments that follow the string 'ssh' are ignored.

```
  bundle exec knife cluster show sandbox-mrflip_fiddle-1 --verbose --verbose
  # very little output
  bundle exec knife cluster show sandbox-mrflip_fiddle-1 -VV
  # very little output

  bundle exec knife cluster show sandbox-mrflip_fiddle-1 -ZZ 
  # ... lots and lots of output ...

  bundle exec knife cluster -Z ssh awesome-box-0 'awesomehood -Z'
  # ... single verbose for knife, and -Z for the awesomehood command
```

I hate monkeying around with ARGV, but a) knife already does so, and b) after some poking around inside knife I don't see a clean way to do this. This only patches up 'knife cluster' commands (things that include Ironfan::KnifeCommon).

### CODE REVIEW

**Comment by mrflip** [comment]
ah, hell. This has commits from both #165 and #166 in it. `git cherry-pick 0f5f1cb` if you're not ready to accept pull #165.

**Comment by temujin9** [comment]
I'm not hot on monkey-patching around upstream bugs; we're altering the interface, adding duplication, and doing things you say you hate, to fix someone else's (hopefully short-lived) minor mistake. Can we instead just mark this particular version of bundler as bad, and not use it here?

I'd love to see a fix for #165, but I don't see anything fixing that in here. Did you mean #147?

**Comment by mrflip** [comment]
I don't know how long the bundler release cycle will be. Would you mind closing the pull request but leaving open the bug? If as you say it's only a short-lived thing then you can close it on next bundler release. Until then I'd like people hitting this bug to at least know how to patch around it. 

It's hell enough to have knife crash with its smug fucking 're-run me with --verbose and maybe I'll tell you about it this time'. This bug means there's no way to actually get it to give you a backtrace at all.

I think(?) you can exclude a gem version in bundler; that would certainly be a gentler fix. Maybe @kornypoet you know how? The interesting question of course is whether bundler will exclude itself.

**Comment by temujin9** [comment]
Fair enough: I can be swayed from my position, if this starts irritating many users. I'll close the pull request and reopen the bug.

**Comment by temujin9** [comment]
Bah: it won't let me dissociate the bug from the request.

**Pull request closed without merging**
